jpotw 첫 주 회고
kujyp/developer-farm pull request #12
Opened 2023-12-11 06:02 UTC by jpotw

이렇게 하는 거 맞나요

2023-12-12 13:42 UTC, kujyp commented on docs/til/jpotw TIL/회고1.md
> +## 2023-12-07
날짜별 기록 좋습니다!

2023-12-12 13:42 UTC, kujyp commented on docs/til/jpotw TIL/회고1.md
> +- 다음에는 gpt4v 갖고 블로그 댓글 자동화 만들어볼 생각
오 이거 궁금하네요 ㅋㅋ

2023-12-12 13:43 UTC, kujyp commented on docs/til/jpotw TIL/회고1.md
> +- 사실 이렇게까지 오래 걸릴 , 시간을 투자할 가치가 있는 플젝인지도 모르겠는데 실력이 부족한 걸 어떡해~
원래 개발자는 쓸데없는것에 시간을 박는 종족입니다 ㅎ

2023-12-12 13:43 UTC, kujyp commented on docs/til/jpotw TIL/회고1.md
> +- 사실 이렇게까지 오래 걸릴 , 시간을 투자할 가치가 있는 플젝인지도 모르겠는데 실력이 부족한 걸 어떡해~
개선이 있다면 ok입니다

2023-12-12 13:44 UTC, kujyp commented on docs/til/jpotw TIL/회고1.md
> +Ctrl / 안 되면 Microsoft 입력기로 바꿔주면 됨
뭣 windows??
windows 버려주시면안될까요

2023-12-12 13:49 UTC, kujyp commented on docs/til/jpotw TIL/회고1.md
> +- 그래도 기록은 해야 댐: 언제, 뭘 했는데, 뭘 하다가 막혀서 뭘 검색했는데, 뭐가 안 나와서, 또 뭘 했는데 ...
기록에대해서는 개발을 잘하는 분들의 기록은 어떤스타일인가 찾아보시면 더 좋습니다

2023-12-12 13:51 UTC, kujyp commented on docs/til/jpotw TIL/회고1.md
> +- 이 README 파일도 내일 다시 깔끔하게 정리하자
til 스타일의 readme는 깔끔하게 수정하기보다
다음날의 til을 더 깔끔한스타일로 쓸수있도록 점진적 향상이 훨씬 좋습니다.

"깔끔하게" 라는게 끝이 없는 작업이라서 그렇습니다

2023-12-12 13:52 UTC, kujyp commented on docs/til/jpotw TIL/회고1.md
> +마지막에 git merge 땜에 미치는줄; 담주에 github 강의 좀 들어야 될듯.
github 강의 보다 깃허브 공식문서 읽기자료를 더 추천드립니다
개발자는 떠 먹여주는 스타일의 영상 의존도를 내릴 필요가 있습니다

2023-12-12 13:52 UTC, kujyp approved these changes

2023-12-12 14:02 UTC, skadjs commented on docs/til/jpotw TIL/회고1.md
> +
경험을 바탕으로 메뉴얼 만든 것 좋아 보입니다! 효율성 증대에 도움될 듯해요.

2023-12-13 05:54 UTC, jpotw commented on docs/til/jpotw TIL/회고1.md
> +- 이 README 파일도 내일 다시 깔끔하게 정리하자
참고하겠습니다

2023-12-13 05:57 UTC, jpotw commented on docs/til/jpotw TIL/회고1.md
> +마지막에 git merge 땜에 미치는줄; 담주에 github 강의 좀 들어야 될듯.
와우 다 읽어주시고 피드백 감사합니다. 잘 참고하겠습니다.

2023-12-23 13:14 UTC, kujyp commented on docs/til/jpotw TIL/회고2.md
> +git pull request 어떻게 하는지 몰랐는데 이제 대충 알았다.
따봉!
회고3에서는 PR 하나 더 만들어봅시다!

2023-12-23 13:32 UTC, kujyp commented on docs/til/jpotw TIL/회고2.md
> +        print(arg)
`type = 튜플로 반환한다.`
부분은 어딘가에서 설명을 읽은것으로 추정됩니다

제가 평소에 공부할때 사용하는 습관 생각나서 첨언합니다

저는 저런부분이 맞는건가?
실제로 돌려보면서 검증해보는편이에요

```python
def input_printer(*args):
    assert isinstance(args, tuple)
    assert args == ("a", "b")

input_printer("a", "b")
```
참고: assert 는 False 가 들어가면 에러가 발생합니다

2023-12-23 13:34 UTC, kujyp commented on docs/til/jpotw TIL/회고2.md
> +```
https://github.com/kujyp/developer-farm/pull/12/commits/6ebd75408b34786ae4eb49107b1fb01a59c4246e#r1435604300 와 같은 예시

```python
def input_printer(**kwargs):
    assert isinstance(kwargs, dict)
    assert kwargs == {"myname": "jp"}

input_printer(myname="jp")
```

2023-12-23 13:35 UTC, kujyp commented on docs/til/jpotw TIL/회고2.md
> +- async def는 뭐임
👍

2023-12-23 13:36 UTC, kujyp requested changes
폴더명을 `docs/til/<GITHUB 계정명>` 으로 변경부탁드려요!
`docs/til/jpotw TIL` => `docs/til/jpotw`

2023-12-23 14:47 UTC, jpotw commented on docs/til/jpotw TIL/회고2.md
> +        print(arg)
감사합니다 !

2023-12-26 16:20 UTC, kujyp approved these changes
👍

2023-12-26 16:20 UTC, merged